var express = require("express");
var cookieParser = require("cookie-parser");
var bodyParser = require("body-parser");
const dotenv = require("dotenv");
const router = require("./src/routes/index.js");
var app = express();
dotenv.config();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.json());
app.use(cookieParser());
router(app);
module.exports = app;
